### ISSUE TITLE
Error pre-rendering file 

### ISSUE THREAD

**Issue by mhadaily** [jonearley/gatsby-plugin-stencil#4]
Hi, 

It seems that the package doesn't work properly anymore. 

I am getting this error 

```js

error pre-rendering file: public/types/index.html with @pkg/components. {
  "level": "error",
  "type": "build",
  "header": "Hydrate Error",
  "messageText": "SyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at
PkgSelect.renderOptionElements
(/Users/dasdas/Projects/pkg/pkg-dds-dsa-guide/node_modules/@pkg/components/hydrate/index.js:8074:16)\n    at
PkgSelect.render
  "relFilePath": null,
  "absFilePath": null,
  "lines": []
}

```

Gatsby CLI version: 3.13.0
Gatsby version: 3.13.0

package: `"gatsby-plugin-stencil": "^0.2.0",`

Can you guess why this can happen?

**Comment by BrunnerLivio** [comment]
Hard to put a finger on what is going wrong here.  Maybe have a look at `node_modules/@pkg/components/hydrate/index.js:8074:16` in your local folder and try to understand what is going on there and add occasional `console.log`-statements of variables. Maybe you'll then get more information what is going on :/ 
[
Maybe also my blog article how I was able to run Stencil together with GatsbyJS might help](https://www.brunnerliv.io/articles/use-stencil-with-gatsbyjs)

**Comment by mhadaily** [comment]
I have investigated a bit more. it seems that your package works ok, that's something related to the Stencil js itself. 

for example, the problem comes with we have to pass an Object to a web component. if we change it to a string like `JSON.stringify(OBJECT)` seems to work well. Although, It seems we are facing some elements that disappear but I guess that's also not your package. 

btw, can you bump your dependencies to gatsby v4 or v3?
